### ISSUE TITLE
how do I go back from two windows to one?

### ISSUE THREAD

**Issue by felipe1982** [peterdotjs/tab-resize#41]
When I press the single large square icon in the app, it makes one window full screen size, but the other (second) windows is still there in the bg.

**Comment by peterdotjs** [comment]
@felipe1982 - apologies for getting back so late, I wasn't getting notifications on this repo. 

If you press the 1x1 layout it'll resize your current window to full screen. It will not touch any of the other windows that you have open.

**Comment by felipe1982** [comment]
If split by the extension itself, how to merge back to one?

**Comment by peterdotjs** [comment]
@felipe1982 you click the "UNDO" button and the windows will merge back into one.
