### ISSUE TITLE
Feature Request: Split current tab into a new window, layout as per usual

### ISSUE THREAD

**Issue by caeldom** [peterdotjs/tab-resize#42]
Not sure if I'm just missing something, but should be an essential feature. When I'm on a tab, I should have the feature to split it into a new window (aligned left/right), leaving the rest of the tabs in the previous window, and layout as per choice. Currently I cannot seem to do this.

Chrome used to have this feature natively, by dragging the tab out of the window and onto a snap option that appeared, which would convert it into a new window and resize both to fit the screen.

**Comment by peterdotjs** [comment]
@caeldom the extension splits your tabs into layouts matching the layout you chose -  as such there are different layouts and sizes of the windows created. 

To achieve what you specifically want only works if you have the tab as the left most tab of the window. 
You can then select the 1x2 or 2x1 layout. The splits happen evenly. Whichever tab you select it is split in half (left and right). Let me know how it goes.

**Comment by caeldom** [comment]
I rarely have a tab on the leftmost side of the window as tabs naturally open to the right. The natural course of action would be to open a tab, and then desire to multitask so activate your extension to move the tab into a new window split to the right (leaving the previous window to split to the left). If I have to move the new tab to be in the leftmost position in the window first, I might as well just split it manually?

**Comment by peterdotjs** [comment]
The way I use it (and many others) is to multitask/compare two windows that were side by side to begin with. Use extension with the popup or shortcut keys and you have 2 windows side by side. 

I feel like I'm still not completely understanding your workflow.

**Comment by caeldom** [comment]
I start off with one window and tabs, and I would like to automate two tasks into one.
1. Create a new window so that I now have two resized windows side by side.
2. Bring the tab that I was on in the first window, into the second window.
Which is what I mean by my title: Split current tab into a new window.

Not sure if you remember but back in 2014 Chrome had a native feature that allowed tabs to be docked, essentially you could drag tab(s) out, drop them to the side of the current window, and Chrome would instantiate a new window for the dropped tabs, and resize both windows to fit the screen, see below.
![image](https://cloud.githubusercontent.com/assets/6067646/9129985/acd0e908-3d21-11e5-9006-2e2d574389a1.png)
This tremendously useful feature was scrapped and I'm trying to look for an alternative, your extension is by far the closest. Great job on what you've got so far! I hope you can now understand the feature I'm looking for.

**Comment by peterdotjs** [comment]
Yup I know what you're talking about. I've used that feature as well. You can achieve the same result but the interface is obviously different (drag and drop versus keyboard and mouse clicking). The tab selection also is slightly different. As the feature is very specific and my extension is meant for a broad case (not just 2 tabs side by side) I don't plan to add an enhancement for this. 

I can suggest additional apps for your workflow. Which OS do you use? Windows and flavors of linux have functionality to easily resize windows (left half, top half, etc.). For Mac OSx there is http://spectacleapp.com/ which is awesome. In my workflow I use the Tab Resize extension in conjunction with these single window resizing apps to quickly compare things/move tabs and windows around. I hope that helps.  Sorry that the existing extension doesn't support what you're asking for.

**Comment by caeldom** [comment]
I use Windows 7. That's ok, I can see how your app is geared for a broader purpose.

If you research "chrome tab docking" you'll find a lot of users really miss this feature in Chrome and there are really no alternatives that provide this feature anywhere, which is a huge shame. Your app conveniently provides half the process which is automatically splitting tabs into windows (although without the drag/drop feature, but that isn't necessary). The only thing that is missing is just moving the highlighted tab into the new window, as opposed to all the tabs to the right of the current, which is what your extension lacks an option to change.
