### ISSUE TITLE
Feature request: create new window on 2nd screen (multimonitor)

### ISSUE THREAD

**Issue by edikus** [peterdotjs/tab-resize#43]
This extension is great! However, one feature I would really like to see is a layout which creates the new window on a second screen. Addiionally, create windows on the same screen, but full size. This allows me to use it to organize tabs into different windows easily.

**Comment by igorlino** [comment]
+1

There is an extension that nearly gets it right in that sense: NiftySplit https://chrome.google.com/webstore/detail/niftysplit/bkmjnlfillpnkgmjnhgklpjjlpjnfeil?hl=en

Its very easy to use, mouse menu to "Open as NiftySplt window".   Then you can drag and drop it where you like it, and it remembers next time. Really nice.

It has problems recognizing a 2nd or 3rd monitor that has different resolution.

It does not have a shortcut that could make it easier, for example replacing the default CTRL-click over a link.

**Comment by peterdotjs** [comment]
Multimonitor support does exist - you do need to select the monitor you want to send it to.
