### ISSUE TITLE
1x2 Split Chrome doesn't work correctly with Windows taskbar at right of screen

### ISSUE THREAD

**Issue by a1ch3mist** [peterdotjs/tab-resize#44]
I have my Windows taskbar at the right side of my screen, not the bottom.  When I do the 1x2 split, the two Chrome windows overlap each other.  It appears that the plug-in is calculating based on the total width of the screen, not accounting for the taskbar width.  This should be an easy fix.

**Comment by peterdotjs** [comment]
Unfortunately specific issues with OS and detecting available screen space.

Merging with https://github.com/peterdotjs/tab-resize/issues/87
