### ISSUE TITLE
Toggle key suggestion

### ISSUE THREAD

**Issue by iori3000** [peterdotjs/tab-resize#52]
Toggle key would be better

I just installed and tested one tap
Missing double Short Cut press like Ctrl+Shift+2 then there is no chance to come back by Ctrl+Shift+Z
because first come back is removed.

I suggest toggle to come back the first or customized size, or option would be good.
If there is no chance to come back it will be a little grief
This is a fast using and tested rough idea, so more good idea for toggle could be better.

**Comment by peterdotjs** [comment]
not clear how this differs from existing undo
