### ISSUE TITLE
Please include open source license with distribution

### ISSUE THREAD

**Issue by kgambrel** [peterdotjs/tab-resize#54]
I work for a large company.  The company requires that any open source code be accompanied by a license.   While our preferred licenses are the permissive MIT or BSD licenses, we're happy with any license identified on https://opensource.org/licenses/category under the heading "Licenses that are popular, widely, or with strong communities".

**Comment by peterdotjs** [comment]
@kgambrel I just added an MIT license.  https://github.com/peterdotjs/tab-resize/blob/master/LICENSE.md 

Thanks!
