### ISSUE TITLE
Is it possible to split startup windows by default?

### ISSUE THREAD

**Issue by maloiselle** [peterdotjs/tab-resize#55]
This isn't an issue so much a a feature request. I'd like to have the option to have two side by side chrome windows on startup with one containing one set of startup pages and the other containing another set. Is this already possible and if not can it be made so?

Thanks!
Mat

**Comment by peterdotjs** [comment]
This should be possible but something that is outside the scope of this chrome extension. You'll need to mess around with your startup configuration and create possibly an extension or script that runs that can automate creating the layout you want.
