### ISSUE TITLE
Centering a Resized Tab

### ISSUE THREAD

**Issue by leej533** [peterdotjs/tab-resize#56]
Hello -

Thanks for creating such a useful extension!  I used it everyday.

Would like you to consider an Align Center option.

Thank you.

**Comment by peterdotjs** [comment]
That's great to hear! I'm not sure what you mean by center align? 1x1 is the only option where a window would be resized to be "center".

**Comment by leej533** [comment]
I apologize for the lack of descriptors in my request - I was a little challenged yesterday.

I frequently use a 1x3 window layout - I have to upload content to three different locations - I align left the first window, align right the second, and align left the third and then move it to the center.

Another thought - align bottom - for 2x2 windows so you can align the lower windows to the corners.

Thanks!

**Comment by peterdotjs** [comment]
@leej533 hmm when you are using the 1x3 layout are you only using one tab? Or do you have "Single Tab" option unchecked?

If you had three tabs and clicked the 1x3 layout on the left most tab. All would be generated for you and you can upload your content to all three independently. Hopefully I understood what you're trying to accomplish.

Let me know if that helps.
