### ISSUE TITLE
Can't get past "I understand" 

### ISSUE THREAD

**Issue by SciMeg** [peterdotjs/tab-resize#57]
The "I understand" button doesn't work on the popup I'm supposed to read before I use the extension, so I can't get past that at all to use it.

**Comment by peterdotjs** [comment]
@meghan81 what OS, chrome version are you using? It sounds like there is a bug but I'm unable to repro. Have you tried to reinstall?

**Comment by peterdotjs** [comment]
Closing as haven't heard any updates.
