### ISSUE TITLE
Window does not close after choosing a splitting option

### ISSUE THREAD

**Issue by nkh** [peterdotjs/tab-resize#58]
If I click on the icon on the tool bar and chose a split, say 1* 2, the window where the split is chose stays open.

**Comment by peterdotjs** [comment]
@nkh are you referring to the chrome extension popup window? Could you provide a gif screenshot?

**Comment by nkh** [comment]
Yes the chrome extension, on a windows machine, if that helps. if you need the screenshot I will try to send one when I have access to windows machine again.
