### ISSUE TITLE
Feature to remove / hide the menu/tabs, search and bookmarksbar of the aligned tabs?

### ISSUE THREAD

**Issue by Cryptamine** [peterdotjs/tab-resize#62]
Can You add the Feature to remove or hide the -- menu/tab, searchfield and bookmarks bar of the different tabs?

for my use of tab-resize it is disturbing and kind of a "space stealer"
there was an chrome/firefox addon called tile-tabs which had that working just great but it also is excluded in the newer version

THX and Regards

**Comment by peterdotjs** [comment]
Unfortunately there aren't any APIs that expose this ability so closing for now until it's exposed.
