### ISSUE TITLE
Option for no window margins

### ISSUE THREAD

**Issue by breyed** [peterdotjs/tab-resize#63]
Currently, when new windows are created, Tab Resize leaves margin around the windows. For example, in a 2x1 config, you can see past the left window onto the desktop (or whatever is behind) on its left, right, and bottom.

This helps make it obvious what is going on, but wastes a bit of screen space, and more importantly, interferes with efficient window management on Windows. On Windows, the key sequence Windows+Left and Windows+Right snap a window only the left or right half of the monitor and move the window between monitors. Since the window placement by Tab Resize isn't quite half the monitor, the first press of a Windows+Left tweaks the window to expand to the full half, and then you have to press Windows+Left to move it somewhere else.

Getting rid of the margin would fix the problem. Then the Tab Resize window positioning would align with Windows' native positioning. Window manipulation would then be quick and intuitive.

If you'd like help with a pull request, let me know. Thanks!

**Comment by peterdotjs** [comment]
@breyed thanks for the detailed description - this is an issue users have complained about for some time but I've been unable to repro and thus have had a difficult time resolving.

What I'm suspecting is that the chrome API that gets window information from the OS of some clients (appears to be mostly Windows related) is incorrect. I haven't experienced the issue on Mac or Linux before.

If you would be willing to help me debug from your client or even better make a pull request I would gladly point you in the right directly.

Could you list your device/OS info and also do the following?
-Open up the extension popup
-Right click anywhere -> inspect element
-Select console in the top navigation of the Developer Tools popup
-Type in the following: 

`resize.display.getInfo(function(displayInfo){console.log(JSON.stringify(displayInfo));});`

This will split out the window information we're getting from chrome. It could be a bug in the extension code but I'm suspect that something weird is happening with Windows OS and Chrome.

Thanks! @breyed

**Comment by breyed** [comment]
I'm running the latest stable Chrome on Windows 10 at 192 DPI. The results of `getInfo` match my monitor's stats.

``` json
[
	{
		"bounds": {
			"height": 900,
			"left": 0,
			"top": 0,
			"width": 1600
		},
		"dpiX": 192,
		"dpiY": 192,
		"hasAccelerometerSupport": false,
		"hasTouchSupport": false,
		"id": "2528732444",
		"isEnabled": true,
		"isInternal": false,
		"isPrimary": true,
		"isUnified": false,
		"mirroringSourceId": "",
		"modes": [],
		"name": "Generic PnP Monitor",
		"overscan": {
			"bottom": 0,
			"left": 0,
			"right": 0,
			"top": 0
		},
		"rotation": 0,
		"workArea": {
			"height": 860,
			"left": 0,
			"top": 0,
			"width": 1600
		}
	}
]
```

Hard to be sure, but it doesn't look like getting the monitor metrics is the issue. Where in the code is the window positioning logic?

**Comment by peterdotjs** [comment]
Merging into https://github.com/peterdotjs/tab-resize/issues/87

Unfortunately specific to Windows OS and how they are currently handling Window management outside of extension sandbox.
