### ISSUE TITLE
Slip across multiple monitors with fixed rows and columns

### ISSUE THREAD

**Issue by j0ales** [peterdotjs/tab-resize#64]
Is posible to split across multiple monitors with fixed rows and columns?
If I use a 2x2 split in a two monitor system, I will obtain two windows in each monitor.
But this feature depends on how monitors are distributed (horizontally or vertically).

**Comment by peterdotjs** [comment]
Currently the extension just uses what it detects as a single monitor from the API. I'm hesitant to make assumptions or add a new settings to handle cases for combining a users's display setup.
