### ISSUE TITLE
Always open new window?

### ISSUE THREAD

**Issue by SamChambers** [peterdotjs/tab-resize#65]
Hopefully I'm not missing something obvious, but is there a way I can ALWAYS open a new window?
 Example: Current window (maintain all tabs as is) resizes to the left half, new window (with new tab) opens to the right half?
I know this will happen naturally if I've selected the rightmost tab, but if any other tab is currently selected, I can only get it to either split the tabs between the two windows (if "Single tab" is selected) or resize the current window to the left (if "Empty tab" is not selected) and open nothing on the right.
Any help would be appreciated. Thanks

**Comment by peterdotjs** [comment]
Not missing anything, this feature currently exist. It's using the order of the tabs to determine how to automate the ordering. I'm hesitant to add more options (tabs to left or always open new window) as I think it will complicate the UI with power user features.

Will keep feedback in mind for future iterations and if there is common feedback. Thanks!
