### ISSUE TITLE
Suggestion for two additional features

### ISSUE THREAD

**Issue by hl24a3** [peterdotjs/tab-resize#67]
Would you consider adding these 2 features to further enhance your already excellent work? Open tabs as popups to further de-clutter wasted space? following code does just that, leaving only top status bar and removing even the address bar.

chrome.browserAction.onClicked.addListener( function(tab) {
    chrome.windows.create({ tabId:tab.id, type:"popup"});
});

Also if you could remove the empty space margin between the windows or maybe give an option to do so in the menu would be great.

An example of Chrome's popup without the address bar
![unnamed](https://user-images.githubusercontent.com/30724183/36664528-e2f07d6e-1adc-11e8-9725-2af9903d591d.png)

**Comment by peterdotjs** [comment]
Thanks for the feedback on the two suggestions.

1) For popup windows it's something I considered early on and while there is saved space from a window perspective - I think most users are using the windows as true windows and not as a temporary popup so I kept it clean and consistent (although with more real estate with regular windows).

2) Unfortunately is an on going issue with Windows OS. Can be tracked here: https://github.com/peterdotjs/tab-resize/issues/87
