### ISSUE TITLE
Add option to hide Tab Resize menu after activating one of the preset configs

### ISSUE THREAD

**Issue by seanbperiod** [peterdotjs/tab-resize#70]
It would be nice for the options menu/window to hide after clicking on one of the presets located at the top. 

Just a minor issue, but very happy with this extension!

**Comment by peterdotjs** [comment]
Appreciate you going to the effort of creating a PR but I want to keep all UI options that are shown to users high engagement. I do understand the use case but since it is very specific I'm hesitant to deploy it for everyone.
