### ISSUE TITLE
Add option to add rows to columns

### ISSUE THREAD

**Issue by seanbperiod** [peterdotjs/tab-resize#72]
In my case, I'd like to have 3 columns, but have the 3rd column be divided into 2 rows, showing 4 tabs total. Is this possible with the current version?

**Comment by peterdotjs** [comment]
This isn't currently possible. The complicated setup would require a rewrite of the implementation and approach for creating layouts but something others have also commented on.

Duplicate of https://github.com/peterdotjs/tab-resize/issues/84
