### ISSUE TITLE
Feature Request: Thirds

### ISSUE THREAD

**Issue by aglaudell** [peterdotjs/tab-resize#75]
Would love the option to split screen into thirds (horiz + vert!) - a useful feature for very large screens or secondary vertical monitors!! Thank you :D

**Comment by mullaney** [comment]
+1 for this. I just recently got a 21:9 screen and would love 1x3 and 1x4.

**Comment by peterdotjs** [comment]
You can already do this with the custom layouts option where you can create 1x3, 1x4 etc.
