### ISSUE TITLE
Feature Request: Current Window Size

### ISSUE THREAD

**Issue by stumphunter** [peterdotjs/tab-resize#77]
Provide an option to split into a window that is the same size as the current window.  Either same window, or a new window.

**Comment by memelet** [comment]
Just installed, and this is immediately what I wanted. I use dual 34inch displays. I never want the browser to take up the entire monitor, that's just too big.

**Comment by peterdotjs** [comment]
Unfortunately this is such a corner case I don't think it would make sense to provide this feature to everyone.
