### ISSUE TITLE
Remove gaps between windows

### ISSUE THREAD

**Issue by Ollystorm** [peterdotjs/tab-resize#79]
![image](https://user-images.githubusercontent.com/41277073/66792525-e3ca2080-ef44-11e9-93d3-2c6bf1a1a105.png)

**Comment by mbehm** [comment]
This extension would probably suit my needs quite well but my OCD just can't handle the huge margins between windows so definitely support this request. Better yet having the margin configurable should suit everyones taste and hopefully not be too hard.

PS. If somebody can point me to where the margin is applied I might make a pull request for it.

**Comment by Ollystorm** [comment]
You might be better off using the tools in Microsoft Power Toys application. It is very powerful and fairly polished.

**Comment by peterdotjs** [comment]
Commented on issue here: https://github.com/peterdotjs/tab-resize/issues/87#issuecomment-768916298

Unfortunately an issue with Windows OS that I have no control over through the extension.

**Comment by peterdotjs** [comment]
Merging into # https://github.com/peterdotjs/tab-resize/issues/87
