### ISSUE TITLE
Bottom align & Multiple Monitor Feature

### ISSUE THREAD

**Issue by roadie** [peterdotjs/tab-resize#81]
1. Would like to see top/bottom align option too because one of my monitors are orientated vertically, and I often wanted to put the window on the bottom half of the screen.

2. Is it possible to send the new tabs to a different monitor and the other ones remain in the original monitor?

3. When I click any of the buttons to move the tabs, the highlighted one remain unmoved. Only the ones to the right are affected. I thought the highlighted tab should move too, is that normal?

**Comment by peterdotjs** [comment]
1. Top and bottom align could be a good enhnacemen

2. IMO this would be a corner case and hard to have a clean UI to implement.

3. Correct it's design so only the tabs to the right are considered.

**Comment by peterdotjs** [comment]
Merging into https://github.com/peterdotjs/tab-resize/issues/38
