### ISSUE TITLE
Privacy Policy?

### ISSUE THREAD

**Issue by Irtemed** [peterdotjs/tab-resize#86]
Hi Peter,
Do you have a privacy policy for the tab resize extension? Sorry I couldn't find it anywhere.
I saw your comment that the extension only uses the "Tab activity" permission, not the history permission, but do you have access to and/or store a user's tab activity? 
thank you, looks like a great extension!
Demetri

**Comment by peterdotjs** [comment]
Hi @Irtemed,

I don't have a formal privacy policy but here is the info I have given to school districts that have reached out in the past (similar info is also on the extension page):

- The extension follows Chrome Store privacy policy: https://developer.chrome.com/webstore/program_policies.
- Anonymous usage tracking is collected (which tab resize button is used, the types of options used). Identifying information like URL information is neither stored nor collected.
- Only I, the developer can see this information. This data is used only for improving the application - info is not shared with anyone else. There is an option in the settings page to opt out of this anonymous tracking.  
- Data is NOT shared with any 3rd party company. 
- Advertising will NEVER be injected as part of the extension. 
- All of the code is open sourced on github (https://github.com/peterdotjs/tab-resize)

Best,
Peter
